// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApp.Data;

#nullable disable

namespace MovieApp.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20250808205049_userSeed")]
    partial class userSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MovieApp.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "BCAC500D-AFF6-47D2-BB76-6430FCC1FE83",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d1f1aabf-39e5-4ae4-9a4e-7a2676e9e9cd",
                            Email = "admin@movieapp.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@MOVIEAPP.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEGQ74H878UZXZ2qrO3PGUCmbDkeR0pVC/YQ0BJQHFv50ks5DsM3WDpIZiB85F9hpRg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2bb56497-5c49-4c01-8bc7-e2df21ef5d53",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "E831C9E1-A746-4326-90FF-80BE4D20790D",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f9b4e15c-1a5f-4c2e-812f-08a6c6135d5a",
                            Email = "user@movieapp.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@MOVIEAPP.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEGQ74H878UZXZ2qrO3PGUCmbDkeR0pVC/YQ0BJQHFv50ks5DsM3WDpIZiB85F9hpRg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "76cbb512-37af-4f7a-aef4-4b52eb2c7618",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("MovieApp.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cast = "",
                            CoverImage = "shawshank.jpg",
                            ReleaseDate = new DateTime(1994, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Two imprisoned men bond over a number of years.",
                            Title = "The Shawshank Redemption",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Cast = "",
                            CoverImage = "godfather.jpg",
                            ReleaseDate = new DateTime(1972, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
                            Title = "The Godfather",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Cast = "",
                            CoverImage = "darkknight.jpg",
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Batman faces the Joker, a criminal mastermind.",
                            Title = "The Dark Knight",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Cast = "",
                            CoverImage = "godfather2.jpg",
                            ReleaseDate = new DateTime(1974, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "The early life and career of Vito Corleone.",
                            Title = "The Godfather Part II",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Cast = "",
                            CoverImage = "12angrymen.jpg",
                            ReleaseDate = new DateTime(1957, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A jury holdout attempts to prevent a miscarriage of justice.",
                            Title = "12 Angry Men",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Cast = "",
                            CoverImage = "schindler.jpg",
                            ReleaseDate = new DateTime(1993, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "In German-occupied Poland during WWII, Oskar Schindler becomes concerned for his Jewish workforce.",
                            Title = "Schindler's List",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Cast = "",
                            CoverImage = "lotr3.jpg",
                            ReleaseDate = new DateTime(2003, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Gandalf and Aragorn lead the World of Men against Sauron's army.",
                            Title = "The Lord of the Rings: The Return of the King",
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Cast = "",
                            CoverImage = "pulpfiction.jpg",
                            ReleaseDate = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "The lives of two mob hitmen, a boxer, and others intertwine.",
                            Title = "Pulp Fiction",
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            Cast = "",
                            CoverImage = "lotr1.jpg",
                            ReleaseDate = new DateTime(2001, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A meek Hobbit sets out on a journey to destroy the One Ring.",
                            Title = "The Lord of the Rings: The Fellowship of the Ring",
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            Cast = "",
                            CoverImage = "forrestgump.jpg",
                            ReleaseDate = new DateTime(1994, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "The presidencies of Kennedy and Johnson, the Vietnam War, and more through the eyes of Forrest Gump.",
                            Title = "Forrest Gump",
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            Cast = "",
                            CoverImage = "fightclub.jpg",
                            ReleaseDate = new DateTime(1999, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "An insomniac office worker forms an underground fight club.",
                            Title = "Fight Club",
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            Cast = "",
                            CoverImage = "inception.jpg",
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A thief who steals corporate secrets through dream-sharing technology.",
                            Title = "Inception",
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            Cast = "",
                            CoverImage = "lotr2.jpg",
                            ReleaseDate = new DateTime(2002, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "While Frodo and Sam edge closer to Mordor, the divided fellowship makes a stand.",
                            Title = "The Lord of the Rings: The Two Towers",
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            Cast = "",
                            CoverImage = "empirestrikesback.jpg",
                            ReleaseDate = new DateTime(1980, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "After the rebels are brutally overpowered, Luke begins Jedi training.",
                            Title = "Star Wars: Episode V - The Empire Strikes Back",
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            Cast = "",
                            CoverImage = "matrix.jpg",
                            ReleaseDate = new DateTime(1999, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A computer hacker learns about the true nature of reality.",
                            Title = "The Matrix",
                            Type = 0
                        },
                        new
                        {
                            Id = 16,
                            Cast = "",
                            CoverImage = "breakingbad.jpg",
                            ReleaseDate = new DateTime(2008, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A high school chemistry teacher turned methamphetamine producer.",
                            Title = "Breaking Bad",
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            Cast = "",
                            CoverImage = "got.jpg",
                            ReleaseDate = new DateTime(2011, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Nine noble families wage war against each other in Westeros.",
                            Title = "Game of Thrones",
                            Type = 1
                        },
                        new
                        {
                            Id = 18,
                            Cast = "",
                            CoverImage = "thewire.jpg",
                            ReleaseDate = new DateTime(2002, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Baltimore drug scene, seen through the eyes of law enforcement and drug dealers.",
                            Title = "The Wire",
                            Type = 1
                        },
                        new
                        {
                            Id = 19,
                            Cast = "",
                            CoverImage = "strangerthings.jpg",
                            ReleaseDate = new DateTime(2016, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A group of young friends witness supernatural forces and secret government exploits.",
                            Title = "Stranger Things",
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            Cast = "",
                            CoverImage = "sopranos.jpg",
                            ReleaseDate = new DateTime(1999, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "New Jersey mob boss Tony Soprano deals with personal and professional issues.",
                            Title = "The Sopranos",
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            Cast = "",
                            CoverImage = "sherlock.jpg",
                            ReleaseDate = new DateTime(2010, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.",
                            Title = "Sherlock",
                            Type = 1
                        },
                        new
                        {
                            Id = 22,
                            Cast = "",
                            CoverImage = "friends.jpg",
                            ReleaseDate = new DateTime(1994, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Follows the personal and professional lives of six twenty to thirty-something friends.",
                            Title = "Friends",
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            Cast = "",
                            CoverImage = "theoffice.jpg",
                            ReleaseDate = new DateTime(2005, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A mockumentary on a group of typical office workers.",
                            Title = "The Office",
                            Type = 1
                        },
                        new
                        {
                            Id = 24,
                            Cast = "",
                            CoverImage = "bettercallsaul.jpg",
                            ReleaseDate = new DateTime(2015, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "The trials and tribulations of criminal lawyer Jimmy McGill.",
                            Title = "Better Call Saul",
                            Type = 1
                        },
                        new
                        {
                            Id = 25,
                            Cast = "",
                            CoverImage = "houseofcards.jpg",
                            ReleaseDate = new DateTime(2013, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A Congressman works with his equally conniving wife to exact revenge.",
                            Title = "House of Cards",
                            Type = 1
                        },
                        new
                        {
                            Id = 26,
                            Cast = "",
                            CoverImage = "chernobyl.jpg",
                            ReleaseDate = new DateTime(2019, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A dramatization of the true story of the Chernobyl nuclear disaster.",
                            Title = "Chernobyl",
                            Type = 1
                        },
                        new
                        {
                            Id = 27,
                            Cast = "",
                            CoverImage = "mandalorian.jpg",
                            ReleaseDate = new DateTime(2019, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A lone gunfighter makes his way through the outer reaches of the galaxy.",
                            Title = "The Mandalorian",
                            Type = 1
                        },
                        new
                        {
                            Id = 28,
                            Cast = "",
                            CoverImage = "lost.jpg",
                            ReleaseDate = new DateTime(2004, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "The survivors of a plane crash are forced to work together.",
                            Title = "Lost",
                            Type = 1
                        },
                        new
                        {
                            Id = 29,
                            Cast = "",
                            CoverImage = "truedetective.jpg",
                            ReleaseDate = new DateTime(2014, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Seasonal anthology series in which police investigations unearth personal and professional secrets.",
                            Title = "True Detective",
                            Type = 1
                        },
                        new
                        {
                            Id = 30,
                            Cast = "",
                            CoverImage = "seinfeld.jpg",
                            ReleaseDate = new DateTime(1989, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "The continuing misadventures of neurotic New York stand-up comedian Jerry Seinfeld.",
                            Title = "Seinfeld",
                            Type = 1
                        });
                });

            modelBuilder.Entity("MovieApp.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 3,
                            MovieId = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 4,
                            MovieId = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 5,
                            MovieId = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 6,
                            MovieId = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 7,
                            MovieId = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 8,
                            MovieId = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 9,
                            MovieId = 1,
                            Value = 5
                        },
                        new
                        {
                            Id = 10,
                            MovieId = 1,
                            Value = 4
                        },
                        new
                        {
                            Id = 11,
                            MovieId = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = 12,
                            MovieId = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = 13,
                            MovieId = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = 14,
                            MovieId = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = 15,
                            MovieId = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = 16,
                            MovieId = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = 17,
                            MovieId = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = 18,
                            MovieId = 2,
                            Value = 5
                        },
                        new
                        {
                            Id = 19,
                            MovieId = 2,
                            Value = 4
                        },
                        new
                        {
                            Id = 20,
                            MovieId = 2,
                            Value = 4
                        },
                        new
                        {
                            Id = 21,
                            MovieId = 3,
                            Value = 5
                        },
                        new
                        {
                            Id = 22,
                            MovieId = 3,
                            Value = 5
                        },
                        new
                        {
                            Id = 23,
                            MovieId = 3,
                            Value = 5
                        },
                        new
                        {
                            Id = 24,
                            MovieId = 3,
                            Value = 5
                        },
                        new
                        {
                            Id = 25,
                            MovieId = 3,
                            Value = 5
                        },
                        new
                        {
                            Id = 26,
                            MovieId = 3,
                            Value = 5
                        },
                        new
                        {
                            Id = 27,
                            MovieId = 3,
                            Value = 5
                        },
                        new
                        {
                            Id = 28,
                            MovieId = 3,
                            Value = 4
                        },
                        new
                        {
                            Id = 29,
                            MovieId = 3,
                            Value = 4
                        },
                        new
                        {
                            Id = 30,
                            MovieId = 3,
                            Value = 4
                        },
                        new
                        {
                            Id = 31,
                            MovieId = 4,
                            Value = 5
                        },
                        new
                        {
                            Id = 32,
                            MovieId = 4,
                            Value = 5
                        },
                        new
                        {
                            Id = 33,
                            MovieId = 4,
                            Value = 5
                        },
                        new
                        {
                            Id = 34,
                            MovieId = 4,
                            Value = 5
                        },
                        new
                        {
                            Id = 35,
                            MovieId = 4,
                            Value = 5
                        },
                        new
                        {
                            Id = 36,
                            MovieId = 4,
                            Value = 5
                        },
                        new
                        {
                            Id = 37,
                            MovieId = 4,
                            Value = 4
                        },
                        new
                        {
                            Id = 38,
                            MovieId = 4,
                            Value = 4
                        },
                        new
                        {
                            Id = 39,
                            MovieId = 4,
                            Value = 4
                        },
                        new
                        {
                            Id = 40,
                            MovieId = 4,
                            Value = 4
                        },
                        new
                        {
                            Id = 41,
                            MovieId = 5,
                            Value = 5
                        },
                        new
                        {
                            Id = 42,
                            MovieId = 5,
                            Value = 5
                        },
                        new
                        {
                            Id = 43,
                            MovieId = 5,
                            Value = 5
                        },
                        new
                        {
                            Id = 44,
                            MovieId = 5,
                            Value = 5
                        },
                        new
                        {
                            Id = 45,
                            MovieId = 5,
                            Value = 5
                        },
                        new
                        {
                            Id = 46,
                            MovieId = 5,
                            Value = 4
                        },
                        new
                        {
                            Id = 47,
                            MovieId = 5,
                            Value = 4
                        },
                        new
                        {
                            Id = 48,
                            MovieId = 5,
                            Value = 4
                        },
                        new
                        {
                            Id = 49,
                            MovieId = 5,
                            Value = 4
                        },
                        new
                        {
                            Id = 50,
                            MovieId = 5,
                            Value = 4
                        },
                        new
                        {
                            Id = 51,
                            MovieId = 6,
                            Value = 5
                        },
                        new
                        {
                            Id = 52,
                            MovieId = 6,
                            Value = 5
                        },
                        new
                        {
                            Id = 53,
                            MovieId = 6,
                            Value = 5
                        },
                        new
                        {
                            Id = 54,
                            MovieId = 6,
                            Value = 5
                        },
                        new
                        {
                            Id = 55,
                            MovieId = 6,
                            Value = 4
                        },
                        new
                        {
                            Id = 56,
                            MovieId = 6,
                            Value = 4
                        },
                        new
                        {
                            Id = 57,
                            MovieId = 6,
                            Value = 4
                        },
                        new
                        {
                            Id = 58,
                            MovieId = 6,
                            Value = 4
                        },
                        new
                        {
                            Id = 59,
                            MovieId = 6,
                            Value = 4
                        },
                        new
                        {
                            Id = 60,
                            MovieId = 6,
                            Value = 4
                        },
                        new
                        {
                            Id = 61,
                            MovieId = 7,
                            Value = 5
                        },
                        new
                        {
                            Id = 62,
                            MovieId = 7,
                            Value = 5
                        },
                        new
                        {
                            Id = 63,
                            MovieId = 7,
                            Value = 5
                        },
                        new
                        {
                            Id = 64,
                            MovieId = 7,
                            Value = 4
                        },
                        new
                        {
                            Id = 65,
                            MovieId = 7,
                            Value = 4
                        },
                        new
                        {
                            Id = 66,
                            MovieId = 7,
                            Value = 4
                        },
                        new
                        {
                            Id = 67,
                            MovieId = 7,
                            Value = 4
                        },
                        new
                        {
                            Id = 68,
                            MovieId = 7,
                            Value = 4
                        },
                        new
                        {
                            Id = 69,
                            MovieId = 7,
                            Value = 4
                        },
                        new
                        {
                            Id = 70,
                            MovieId = 7,
                            Value = 4
                        },
                        new
                        {
                            Id = 71,
                            MovieId = 8,
                            Value = 5
                        },
                        new
                        {
                            Id = 72,
                            MovieId = 8,
                            Value = 5
                        },
                        new
                        {
                            Id = 73,
                            MovieId = 8,
                            Value = 4
                        },
                        new
                        {
                            Id = 74,
                            MovieId = 8,
                            Value = 4
                        },
                        new
                        {
                            Id = 75,
                            MovieId = 8,
                            Value = 4
                        },
                        new
                        {
                            Id = 76,
                            MovieId = 8,
                            Value = 4
                        },
                        new
                        {
                            Id = 77,
                            MovieId = 8,
                            Value = 4
                        },
                        new
                        {
                            Id = 78,
                            MovieId = 8,
                            Value = 4
                        },
                        new
                        {
                            Id = 79,
                            MovieId = 8,
                            Value = 4
                        },
                        new
                        {
                            Id = 80,
                            MovieId = 8,
                            Value = 4
                        },
                        new
                        {
                            Id = 81,
                            MovieId = 9,
                            Value = 5
                        },
                        new
                        {
                            Id = 82,
                            MovieId = 9,
                            Value = 4
                        },
                        new
                        {
                            Id = 83,
                            MovieId = 9,
                            Value = 4
                        },
                        new
                        {
                            Id = 84,
                            MovieId = 9,
                            Value = 4
                        },
                        new
                        {
                            Id = 85,
                            MovieId = 9,
                            Value = 4
                        },
                        new
                        {
                            Id = 86,
                            MovieId = 9,
                            Value = 4
                        },
                        new
                        {
                            Id = 87,
                            MovieId = 9,
                            Value = 4
                        },
                        new
                        {
                            Id = 88,
                            MovieId = 9,
                            Value = 4
                        },
                        new
                        {
                            Id = 89,
                            MovieId = 9,
                            Value = 4
                        },
                        new
                        {
                            Id = 90,
                            MovieId = 9,
                            Value = 4
                        },
                        new
                        {
                            Id = 91,
                            MovieId = 10,
                            Value = 4
                        },
                        new
                        {
                            Id = 92,
                            MovieId = 10,
                            Value = 4
                        },
                        new
                        {
                            Id = 93,
                            MovieId = 10,
                            Value = 4
                        },
                        new
                        {
                            Id = 94,
                            MovieId = 10,
                            Value = 4
                        },
                        new
                        {
                            Id = 95,
                            MovieId = 10,
                            Value = 4
                        },
                        new
                        {
                            Id = 96,
                            MovieId = 10,
                            Value = 4
                        },
                        new
                        {
                            Id = 97,
                            MovieId = 10,
                            Value = 4
                        },
                        new
                        {
                            Id = 98,
                            MovieId = 10,
                            Value = 4
                        },
                        new
                        {
                            Id = 99,
                            MovieId = 10,
                            Value = 4
                        },
                        new
                        {
                            Id = 100,
                            MovieId = 10,
                            Value = 4
                        },
                        new
                        {
                            Id = 101,
                            MovieId = 11,
                            Value = 4
                        },
                        new
                        {
                            Id = 102,
                            MovieId = 11,
                            Value = 4
                        },
                        new
                        {
                            Id = 103,
                            MovieId = 11,
                            Value = 4
                        },
                        new
                        {
                            Id = 104,
                            MovieId = 11,
                            Value = 4
                        },
                        new
                        {
                            Id = 105,
                            MovieId = 11,
                            Value = 4
                        },
                        new
                        {
                            Id = 106,
                            MovieId = 11,
                            Value = 4
                        },
                        new
                        {
                            Id = 107,
                            MovieId = 11,
                            Value = 4
                        },
                        new
                        {
                            Id = 108,
                            MovieId = 11,
                            Value = 4
                        },
                        new
                        {
                            Id = 109,
                            MovieId = 11,
                            Value = 4
                        },
                        new
                        {
                            Id = 110,
                            MovieId = 11,
                            Value = 3
                        },
                        new
                        {
                            Id = 111,
                            MovieId = 12,
                            Value = 4
                        },
                        new
                        {
                            Id = 112,
                            MovieId = 12,
                            Value = 4
                        },
                        new
                        {
                            Id = 113,
                            MovieId = 12,
                            Value = 4
                        },
                        new
                        {
                            Id = 114,
                            MovieId = 12,
                            Value = 4
                        },
                        new
                        {
                            Id = 115,
                            MovieId = 12,
                            Value = 4
                        },
                        new
                        {
                            Id = 116,
                            MovieId = 12,
                            Value = 4
                        },
                        new
                        {
                            Id = 117,
                            MovieId = 12,
                            Value = 4
                        },
                        new
                        {
                            Id = 118,
                            MovieId = 12,
                            Value = 4
                        },
                        new
                        {
                            Id = 119,
                            MovieId = 12,
                            Value = 3
                        },
                        new
                        {
                            Id = 120,
                            MovieId = 12,
                            Value = 3
                        },
                        new
                        {
                            Id = 121,
                            MovieId = 13,
                            Value = 4
                        },
                        new
                        {
                            Id = 122,
                            MovieId = 13,
                            Value = 4
                        },
                        new
                        {
                            Id = 123,
                            MovieId = 13,
                            Value = 4
                        },
                        new
                        {
                            Id = 124,
                            MovieId = 13,
                            Value = 4
                        },
                        new
                        {
                            Id = 125,
                            MovieId = 13,
                            Value = 4
                        },
                        new
                        {
                            Id = 126,
                            MovieId = 13,
                            Value = 4
                        },
                        new
                        {
                            Id = 127,
                            MovieId = 13,
                            Value = 4
                        },
                        new
                        {
                            Id = 128,
                            MovieId = 13,
                            Value = 3
                        },
                        new
                        {
                            Id = 129,
                            MovieId = 13,
                            Value = 3
                        },
                        new
                        {
                            Id = 130,
                            MovieId = 13,
                            Value = 3
                        },
                        new
                        {
                            Id = 131,
                            MovieId = 14,
                            Value = 4
                        },
                        new
                        {
                            Id = 132,
                            MovieId = 14,
                            Value = 4
                        },
                        new
                        {
                            Id = 133,
                            MovieId = 14,
                            Value = 4
                        },
                        new
                        {
                            Id = 134,
                            MovieId = 14,
                            Value = 4
                        },
                        new
                        {
                            Id = 135,
                            MovieId = 14,
                            Value = 4
                        },
                        new
                        {
                            Id = 136,
                            MovieId = 14,
                            Value = 4
                        },
                        new
                        {
                            Id = 137,
                            MovieId = 14,
                            Value = 3
                        },
                        new
                        {
                            Id = 138,
                            MovieId = 14,
                            Value = 3
                        },
                        new
                        {
                            Id = 139,
                            MovieId = 14,
                            Value = 3
                        },
                        new
                        {
                            Id = 140,
                            MovieId = 14,
                            Value = 3
                        },
                        new
                        {
                            Id = 141,
                            MovieId = 15,
                            Value = 4
                        },
                        new
                        {
                            Id = 142,
                            MovieId = 15,
                            Value = 4
                        },
                        new
                        {
                            Id = 143,
                            MovieId = 15,
                            Value = 4
                        },
                        new
                        {
                            Id = 144,
                            MovieId = 15,
                            Value = 4
                        },
                        new
                        {
                            Id = 145,
                            MovieId = 15,
                            Value = 4
                        },
                        new
                        {
                            Id = 146,
                            MovieId = 15,
                            Value = 3
                        },
                        new
                        {
                            Id = 147,
                            MovieId = 15,
                            Value = 3
                        },
                        new
                        {
                            Id = 148,
                            MovieId = 15,
                            Value = 3
                        },
                        new
                        {
                            Id = 149,
                            MovieId = 15,
                            Value = 3
                        },
                        new
                        {
                            Id = 150,
                            MovieId = 15,
                            Value = 3
                        },
                        new
                        {
                            Id = 151,
                            MovieId = 16,
                            Value = 5
                        },
                        new
                        {
                            Id = 152,
                            MovieId = 16,
                            Value = 5
                        },
                        new
                        {
                            Id = 153,
                            MovieId = 16,
                            Value = 5
                        },
                        new
                        {
                            Id = 154,
                            MovieId = 16,
                            Value = 5
                        },
                        new
                        {
                            Id = 155,
                            MovieId = 16,
                            Value = 5
                        },
                        new
                        {
                            Id = 156,
                            MovieId = 16,
                            Value = 4
                        },
                        new
                        {
                            Id = 157,
                            MovieId = 16,
                            Value = 4
                        },
                        new
                        {
                            Id = 158,
                            MovieId = 16,
                            Value = 4
                        },
                        new
                        {
                            Id = 159,
                            MovieId = 16,
                            Value = 4
                        },
                        new
                        {
                            Id = 160,
                            MovieId = 16,
                            Value = 4
                        },
                        new
                        {
                            Id = 161,
                            MovieId = 17,
                            Value = 5
                        },
                        new
                        {
                            Id = 162,
                            MovieId = 17,
                            Value = 5
                        },
                        new
                        {
                            Id = 163,
                            MovieId = 17,
                            Value = 5
                        },
                        new
                        {
                            Id = 164,
                            MovieId = 17,
                            Value = 5
                        },
                        new
                        {
                            Id = 165,
                            MovieId = 17,
                            Value = 4
                        },
                        new
                        {
                            Id = 166,
                            MovieId = 17,
                            Value = 4
                        },
                        new
                        {
                            Id = 167,
                            MovieId = 17,
                            Value = 4
                        },
                        new
                        {
                            Id = 168,
                            MovieId = 17,
                            Value = 4
                        },
                        new
                        {
                            Id = 169,
                            MovieId = 17,
                            Value = 4
                        },
                        new
                        {
                            Id = 170,
                            MovieId = 17,
                            Value = 4
                        },
                        new
                        {
                            Id = 171,
                            MovieId = 18,
                            Value = 5
                        },
                        new
                        {
                            Id = 172,
                            MovieId = 18,
                            Value = 5
                        },
                        new
                        {
                            Id = 173,
                            MovieId = 18,
                            Value = 5
                        },
                        new
                        {
                            Id = 174,
                            MovieId = 18,
                            Value = 4
                        },
                        new
                        {
                            Id = 175,
                            MovieId = 18,
                            Value = 4
                        },
                        new
                        {
                            Id = 176,
                            MovieId = 18,
                            Value = 4
                        },
                        new
                        {
                            Id = 177,
                            MovieId = 18,
                            Value = 4
                        },
                        new
                        {
                            Id = 178,
                            MovieId = 18,
                            Value = 4
                        },
                        new
                        {
                            Id = 179,
                            MovieId = 18,
                            Value = 4
                        },
                        new
                        {
                            Id = 180,
                            MovieId = 18,
                            Value = 4
                        },
                        new
                        {
                            Id = 181,
                            MovieId = 19,
                            Value = 5
                        },
                        new
                        {
                            Id = 182,
                            MovieId = 19,
                            Value = 5
                        },
                        new
                        {
                            Id = 183,
                            MovieId = 19,
                            Value = 4
                        },
                        new
                        {
                            Id = 184,
                            MovieId = 19,
                            Value = 4
                        },
                        new
                        {
                            Id = 185,
                            MovieId = 19,
                            Value = 4
                        },
                        new
                        {
                            Id = 186,
                            MovieId = 19,
                            Value = 4
                        },
                        new
                        {
                            Id = 187,
                            MovieId = 19,
                            Value = 4
                        },
                        new
                        {
                            Id = 188,
                            MovieId = 19,
                            Value = 4
                        },
                        new
                        {
                            Id = 189,
                            MovieId = 19,
                            Value = 4
                        },
                        new
                        {
                            Id = 190,
                            MovieId = 19,
                            Value = 4
                        },
                        new
                        {
                            Id = 191,
                            MovieId = 20,
                            Value = 5
                        },
                        new
                        {
                            Id = 192,
                            MovieId = 20,
                            Value = 4
                        },
                        new
                        {
                            Id = 193,
                            MovieId = 20,
                            Value = 4
                        },
                        new
                        {
                            Id = 194,
                            MovieId = 20,
                            Value = 4
                        },
                        new
                        {
                            Id = 195,
                            MovieId = 20,
                            Value = 4
                        },
                        new
                        {
                            Id = 196,
                            MovieId = 20,
                            Value = 4
                        },
                        new
                        {
                            Id = 197,
                            MovieId = 20,
                            Value = 4
                        },
                        new
                        {
                            Id = 198,
                            MovieId = 20,
                            Value = 4
                        },
                        new
                        {
                            Id = 199,
                            MovieId = 20,
                            Value = 4
                        },
                        new
                        {
                            Id = 200,
                            MovieId = 20,
                            Value = 4
                        },
                        new
                        {
                            Id = 201,
                            MovieId = 21,
                            Value = 4
                        },
                        new
                        {
                            Id = 202,
                            MovieId = 21,
                            Value = 4
                        },
                        new
                        {
                            Id = 203,
                            MovieId = 21,
                            Value = 4
                        },
                        new
                        {
                            Id = 204,
                            MovieId = 21,
                            Value = 4
                        },
                        new
                        {
                            Id = 205,
                            MovieId = 21,
                            Value = 4
                        },
                        new
                        {
                            Id = 206,
                            MovieId = 21,
                            Value = 4
                        },
                        new
                        {
                            Id = 207,
                            MovieId = 21,
                            Value = 4
                        },
                        new
                        {
                            Id = 208,
                            MovieId = 21,
                            Value = 4
                        },
                        new
                        {
                            Id = 209,
                            MovieId = 21,
                            Value = 4
                        },
                        new
                        {
                            Id = 210,
                            MovieId = 21,
                            Value = 4
                        },
                        new
                        {
                            Id = 211,
                            MovieId = 22,
                            Value = 4
                        },
                        new
                        {
                            Id = 212,
                            MovieId = 22,
                            Value = 4
                        },
                        new
                        {
                            Id = 213,
                            MovieId = 22,
                            Value = 4
                        },
                        new
                        {
                            Id = 214,
                            MovieId = 22,
                            Value = 4
                        },
                        new
                        {
                            Id = 215,
                            MovieId = 22,
                            Value = 4
                        },
                        new
                        {
                            Id = 216,
                            MovieId = 22,
                            Value = 4
                        },
                        new
                        {
                            Id = 217,
                            MovieId = 22,
                            Value = 4
                        },
                        new
                        {
                            Id = 218,
                            MovieId = 22,
                            Value = 4
                        },
                        new
                        {
                            Id = 219,
                            MovieId = 22,
                            Value = 4
                        },
                        new
                        {
                            Id = 220,
                            MovieId = 22,
                            Value = 3
                        },
                        new
                        {
                            Id = 221,
                            MovieId = 23,
                            Value = 4
                        },
                        new
                        {
                            Id = 222,
                            MovieId = 23,
                            Value = 4
                        },
                        new
                        {
                            Id = 223,
                            MovieId = 23,
                            Value = 4
                        },
                        new
                        {
                            Id = 224,
                            MovieId = 23,
                            Value = 4
                        },
                        new
                        {
                            Id = 225,
                            MovieId = 23,
                            Value = 4
                        },
                        new
                        {
                            Id = 226,
                            MovieId = 23,
                            Value = 4
                        },
                        new
                        {
                            Id = 227,
                            MovieId = 23,
                            Value = 4
                        },
                        new
                        {
                            Id = 228,
                            MovieId = 23,
                            Value = 4
                        },
                        new
                        {
                            Id = 229,
                            MovieId = 23,
                            Value = 3
                        },
                        new
                        {
                            Id = 230,
                            MovieId = 23,
                            Value = 3
                        },
                        new
                        {
                            Id = 231,
                            MovieId = 24,
                            Value = 4
                        },
                        new
                        {
                            Id = 232,
                            MovieId = 24,
                            Value = 4
                        },
                        new
                        {
                            Id = 233,
                            MovieId = 24,
                            Value = 4
                        },
                        new
                        {
                            Id = 234,
                            MovieId = 24,
                            Value = 4
                        },
                        new
                        {
                            Id = 235,
                            MovieId = 24,
                            Value = 4
                        },
                        new
                        {
                            Id = 236,
                            MovieId = 24,
                            Value = 4
                        },
                        new
                        {
                            Id = 237,
                            MovieId = 24,
                            Value = 4
                        },
                        new
                        {
                            Id = 238,
                            MovieId = 24,
                            Value = 3
                        },
                        new
                        {
                            Id = 239,
                            MovieId = 24,
                            Value = 3
                        },
                        new
                        {
                            Id = 240,
                            MovieId = 24,
                            Value = 3
                        },
                        new
                        {
                            Id = 241,
                            MovieId = 25,
                            Value = 4
                        },
                        new
                        {
                            Id = 242,
                            MovieId = 25,
                            Value = 4
                        },
                        new
                        {
                            Id = 243,
                            MovieId = 25,
                            Value = 4
                        },
                        new
                        {
                            Id = 244,
                            MovieId = 25,
                            Value = 4
                        },
                        new
                        {
                            Id = 245,
                            MovieId = 25,
                            Value = 4
                        },
                        new
                        {
                            Id = 246,
                            MovieId = 25,
                            Value = 4
                        },
                        new
                        {
                            Id = 247,
                            MovieId = 25,
                            Value = 3
                        },
                        new
                        {
                            Id = 248,
                            MovieId = 25,
                            Value = 3
                        },
                        new
                        {
                            Id = 249,
                            MovieId = 25,
                            Value = 3
                        },
                        new
                        {
                            Id = 250,
                            MovieId = 25,
                            Value = 3
                        },
                        new
                        {
                            Id = 251,
                            MovieId = 26,
                            Value = 4
                        },
                        new
                        {
                            Id = 252,
                            MovieId = 26,
                            Value = 4
                        },
                        new
                        {
                            Id = 253,
                            MovieId = 26,
                            Value = 4
                        },
                        new
                        {
                            Id = 254,
                            MovieId = 26,
                            Value = 4
                        },
                        new
                        {
                            Id = 255,
                            MovieId = 26,
                            Value = 4
                        },
                        new
                        {
                            Id = 256,
                            MovieId = 26,
                            Value = 3
                        },
                        new
                        {
                            Id = 257,
                            MovieId = 26,
                            Value = 3
                        },
                        new
                        {
                            Id = 258,
                            MovieId = 26,
                            Value = 3
                        },
                        new
                        {
                            Id = 259,
                            MovieId = 26,
                            Value = 3
                        },
                        new
                        {
                            Id = 260,
                            MovieId = 26,
                            Value = 3
                        },
                        new
                        {
                            Id = 261,
                            MovieId = 27,
                            Value = 4
                        },
                        new
                        {
                            Id = 262,
                            MovieId = 27,
                            Value = 4
                        },
                        new
                        {
                            Id = 263,
                            MovieId = 27,
                            Value = 4
                        },
                        new
                        {
                            Id = 264,
                            MovieId = 27,
                            Value = 4
                        },
                        new
                        {
                            Id = 265,
                            MovieId = 27,
                            Value = 3
                        },
                        new
                        {
                            Id = 266,
                            MovieId = 27,
                            Value = 3
                        },
                        new
                        {
                            Id = 267,
                            MovieId = 27,
                            Value = 3
                        },
                        new
                        {
                            Id = 268,
                            MovieId = 27,
                            Value = 3
                        },
                        new
                        {
                            Id = 269,
                            MovieId = 27,
                            Value = 3
                        },
                        new
                        {
                            Id = 270,
                            MovieId = 27,
                            Value = 3
                        },
                        new
                        {
                            Id = 271,
                            MovieId = 28,
                            Value = 4
                        },
                        new
                        {
                            Id = 272,
                            MovieId = 28,
                            Value = 4
                        },
                        new
                        {
                            Id = 273,
                            MovieId = 28,
                            Value = 4
                        },
                        new
                        {
                            Id = 274,
                            MovieId = 28,
                            Value = 3
                        },
                        new
                        {
                            Id = 275,
                            MovieId = 28,
                            Value = 3
                        },
                        new
                        {
                            Id = 276,
                            MovieId = 28,
                            Value = 3
                        },
                        new
                        {
                            Id = 277,
                            MovieId = 28,
                            Value = 3
                        },
                        new
                        {
                            Id = 278,
                            MovieId = 28,
                            Value = 3
                        },
                        new
                        {
                            Id = 279,
                            MovieId = 28,
                            Value = 3
                        },
                        new
                        {
                            Id = 280,
                            MovieId = 28,
                            Value = 3
                        },
                        new
                        {
                            Id = 281,
                            MovieId = 29,
                            Value = 4
                        },
                        new
                        {
                            Id = 282,
                            MovieId = 29,
                            Value = 4
                        },
                        new
                        {
                            Id = 283,
                            MovieId = 29,
                            Value = 3
                        },
                        new
                        {
                            Id = 284,
                            MovieId = 29,
                            Value = 3
                        },
                        new
                        {
                            Id = 285,
                            MovieId = 29,
                            Value = 3
                        },
                        new
                        {
                            Id = 286,
                            MovieId = 29,
                            Value = 3
                        },
                        new
                        {
                            Id = 287,
                            MovieId = 29,
                            Value = 3
                        },
                        new
                        {
                            Id = 288,
                            MovieId = 29,
                            Value = 3
                        },
                        new
                        {
                            Id = 289,
                            MovieId = 29,
                            Value = 3
                        },
                        new
                        {
                            Id = 290,
                            MovieId = 29,
                            Value = 3
                        },
                        new
                        {
                            Id = 291,
                            MovieId = 30,
                            Value = 4
                        },
                        new
                        {
                            Id = 292,
                            MovieId = 30,
                            Value = 3
                        },
                        new
                        {
                            Id = 293,
                            MovieId = 30,
                            Value = 3
                        },
                        new
                        {
                            Id = 294,
                            MovieId = 30,
                            Value = 3
                        },
                        new
                        {
                            Id = 295,
                            MovieId = 30,
                            Value = 3
                        },
                        new
                        {
                            Id = 296,
                            MovieId = 30,
                            Value = 3
                        },
                        new
                        {
                            Id = 297,
                            MovieId = 30,
                            Value = 3
                        },
                        new
                        {
                            Id = 298,
                            MovieId = 30,
                            Value = 3
                        },
                        new
                        {
                            Id = 299,
                            MovieId = 30,
                            Value = 3
                        },
                        new
                        {
                            Id = 300,
                            MovieId = 30,
                            Value = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MovieApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MovieApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MovieApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieApp.Models.Rating", b =>
                {
                    b.HasOne("MovieApp.Models.Movie", "Movie")
                        .WithMany("Ratings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieApp.Models.Movie", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
